/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ManualsRouteImport } from './routes/manuals'
import { Route as MachinesRouteImport } from './routes/machines'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManualsManualIdRouteImport } from './routes/manuals.$manualId'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualsRoute = ManualsRouteImport.update({
  id: '/manuals',
  path: '/manuals',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesRoute = MachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualsManualIdRoute = ManualsManualIdRouteImport.update({
  id: '/$manualId',
  path: '/$manualId',
  getParentRoute: () => ManualsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/history': typeof HistoryRoute
  '/machines': typeof MachinesRoute
  '/manuals': typeof ManualsRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/manuals/$manualId': typeof ManualsManualIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/history': typeof HistoryRoute
  '/machines': typeof MachinesRoute
  '/manuals': typeof ManualsRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/manuals/$manualId': typeof ManualsManualIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/history': typeof HistoryRoute
  '/machines': typeof MachinesRoute
  '/manuals': typeof ManualsRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/manuals/$manualId': typeof ManualsManualIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/history'
    | '/machines'
    | '/manuals'
    | '/search'
    | '/settings'
    | '/upload'
    | '/manuals/$manualId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cases'
    | '/history'
    | '/machines'
    | '/manuals'
    | '/search'
    | '/settings'
    | '/upload'
    | '/manuals/$manualId'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/history'
    | '/machines'
    | '/manuals'
    | '/search'
    | '/settings'
    | '/upload'
    | '/manuals/$manualId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRoute
  HistoryRoute: typeof HistoryRoute
  MachinesRoute: typeof MachinesRoute
  ManualsRoute: typeof ManualsRouteWithChildren
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manuals': {
      id: '/manuals'
      path: '/manuals'
      fullPath: '/manuals'
      preLoaderRoute: typeof ManualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines': {
      id: '/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof MachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manuals/$manualId': {
      id: '/manuals/$manualId'
      path: '/$manualId'
      fullPath: '/manuals/$manualId'
      preLoaderRoute: typeof ManualsManualIdRouteImport
      parentRoute: typeof ManualsRoute
    }
  }
}

interface ManualsRouteChildren {
  ManualsManualIdRoute: typeof ManualsManualIdRoute
}

const ManualsRouteChildren: ManualsRouteChildren = {
  ManualsManualIdRoute: ManualsManualIdRoute,
}

const ManualsRouteWithChildren =
  ManualsRoute._addFileChildren(ManualsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRoute,
  HistoryRoute: HistoryRoute,
  MachinesRoute: MachinesRoute,
  ManualsRoute: ManualsRouteWithChildren,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
